astuto/config/routes.rb
Rails.application.routes.draw do
  if !Rails.application.multi_tenancy?
    mount Rswag::Api::Engine => '/api-docs'
  end

  if Rails.application.multi_tenancy?
    constraints subdomain: 'showcase' do
      root to: 'static_pages#showcase', as: :showcase
    end

    constraints subdomain: 'api' do
      mount Rswag::Api::Engine => '/api-docs'
    end

    constraints subdomain: 'login' do
      get '/signup', to: 'tenants#new'
      get '/is_available', to: 'tenants#is_available'
      
      resource :tenants, only: [:create]
    end

    constraints subdomain: 'billing' do
      get '/billing', to: 'billing#index'
      get '/billing/return', to: 'billing#return'
      post '/create_checkout_session', to: 'billing#create_checkout_session'
      get '/session_status', to: 'billing#session_status'
      post '/webhook', to: 'billing#webhook'
    end
  end

  constraints subdomain: /.*/ do
    root to: 'static_pages#root'
    
    get '/roadmap', to: 'static_pages#roadmap'
    get '/embedded_roadmap', to: 'static_pages#embedded_roadmap'
    get '/pending-tenant', to: 'static_pages#pending_tenant'
    get '/blocked-tenant', to: 'static_pages#blocked_tenant'
    
    get '/request_billing_page', to: 'billing#request_billing_page'
    
    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :sessions => 'sessions',
      :passwords => 'passwords'
    }

    devise_scope :user do
      get '/users/send_set_password_instructions', to: 'registrations#send_set_password_instructions', as: :send_set_password_instructions
    end
    
    resources :tenants, only: [:show, :update]
    resources :users, only: [:index, :update]
    resources :o_auths, only: [:index, :create, :update, :destroy] do
      resource :tenant_default_o_auths, only: [:create, :destroy]
    end
    get '/o_auths/:id/start', to: 'o_auths#start', as: :o_auth_start
    get '/o_auths/:id/callback', to: 'o_auths#callback', as: :o_auth_callback
    get '/o_auths/sign_in_from_oauth_token', to: 'o_auths#sign_in_from_oauth_token', as: :o_auth_sign_in_from_oauth_token
  
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
      resources :follows, only: [:index]
      resource :likes, only: [:create, :destroy]
      resources :likes, only: [:index]
      resources :comments, only: [:index, :create, :update, :destroy]
      resources :post_status_changes, only: [:index]

      get '/moderation', on: :collection, to: 'posts#moderation'
    end
    
    resources :boards, only: [:index, :create, :update, :destroy, :show] do
      patch 'update_order', on: :collection
    end
  
    resources :post_statuses, only: [:index, :create, :update, :destroy] do
      patch 'update_order', on: :collection
    end

    resources :invitations, only: [:create]
    post '/invitations/test', to: 'invitations#test', as: :invitation_test

    resources :api_keys, only: [:create]
  
    namespace :site_settings do
      get 'general'
      get 'authentication'
      get 'boards'
      get 'post_statuses'
      get 'roadmap'
      get 'invitations'
      get 'appearance'
    end

    namespace :moderation do
      get 'feedback'
      get 'users'
    end

    # API routes
    namespace :api do
      namespace :v1 do
        resources :boards, only: [:index, :show, :create]
        resources :post_statuses, only: [:index]
        resources :posts, only: [:index, :show, :create, :update, :destroy] do
          member do
            put :update_board, :update_status, :approve, :reject
          end
        end
        resources :comments, only: [:index, :show, :create, :update, :destroy] do
          member do
            put :mark_as_post_update, :unmark_as_post_update
          end
        end
        resources :votes, only: [:index, :show, :create, :destroy], controller: 'likes'
        resources :users, only: [:index, :show, :create] do
          collection do
            get :get_by_email, controller: 'users', action: 'show_by_email'
          end
          member do
            put :block
          end
        end 
      end
    end
  end

  # Healthcheck endpoint
  get '/health', to: proc {
    Tenant.first # to make sure db works
    [200, {}, ['success']]
  }
end

astuto/app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice container alert alert-primary"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert container alert-danger"><%= alert %></p>
<% end %>

astuto/app/views/layouts/_boards_nav_section.html.erb
<% if @tenant_setting.collapse_boards_in_header == 'always_collapse' %>
  <li class="navbar-nav nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Boards
    </a>
    <ul class="dropdown-menu boards-dropdown" aria-labelledby="navbarDropdown">
      <% boards.each do |board| %>
        <li>
          <%= link_to board.name, @header_full_urls ? get_url_for(method(:board_url), resource: board) : board_path(board), class: 'dropdown-item' %>
        </li>
      <% end %>
    </ul>
<% else %>
  <% boards.each do |board| %>
    <li class="nav-item<%= board.id == @board.id ? ' active' : '' unless @board.nil? %>">
      <%= link_to board.name, @header_full_urls ? get_url_for(method(:board_url), resource: board) : board_path(board), class: 'nav-link' %>
    </li>
  <% end %>
<% end %>

astuto/app/views/layouts/_header.html.erb
<nav class="header">
  <div class="container">
    <%=
      link_to get_url_for_logo, class: "brand#{@tenant_setting.logo_links_to == 'nothing' ? ' brandDisabled' : ''}", tabindex: @tenant_setting.logo_links_to == 'nothing' ? -1 : 0 do
        app_name = content_tag :span, @tenant.site_name
        logo = image_tag(@tenant.site_logo ? @tenant.site_logo : "", class: 'logo', skip_pipeline: true)

        if @tenant_setting.brand_display == "name_and_logo"
          logo + app_name
        elsif @tenant_setting.brand_display == "name_only"
          app_name
        elsif @tenant_setting.brand_display == "logo_only"
          logo
        end
      end
    %>

    <button
      class="navbarToggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="boardsNav">
        <% if @tenant_setting.show_roadmap_in_header %>
          <li class="nav-item<%= (current_page?(roadmap_path) or (@tenant_setting.root_board_id == 0 and current_page?(root_path))) ? ' active' : '' %>">
            <%= link_to t('roadmap.title'), @header_full_urls ? get_url_for(method(:roadmap_url)) : roadmap_path, class: 'nav-link' %>
          </li>
        <% end %>
        
        <%= render 'layouts/boards_nav_section', boards: @boards unless @boards.nil? %>
      </ul>

      <ul class="profileNav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="profileToggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_user.gravatar_url, class: 'gravatar', alt: current_user.full_name, size: 24) %>
              <span class="fullname"><%= current_user.full_name.truncate(24) %></span>
              <% if current_user.moderator? && Post.pending.length > 0 %>
                <span class="notificationDot notificationDotTop"><%= Post.pending.length %></span>
              <% end %>
            </a>
            <div class="dropdown-menu" onclick="event.stopPropagation()" aria-labelledby="navbarDropdown">
              <% if current_user.moderator? %>
                <h6 class="dropdown-header"><%= t('header.menu.administration_header') %></h6>
                <% if current_user.admin? or current_user.owner? %>
                  <%=
                    link_to t('header.menu.site_settings'),
                      @header_full_urls ? get_url_for(method(:site_settings_general_url)) : site_settings_general_path,
                      class: 'dropdown-item siteSettingsDropdown'
                  %>
                <% end %>

                <%= link_to @header_full_urls ? get_url_for(method(:moderation_feedback_url)) : moderation_feedback_path, class: 'dropdown-item moderationDropdown' do %>
                  <%= t('header.menu.moderation') %>
                  <% if Post.pending.length > 0 %>
                    &nbsp;
                    <span class="notificationDot"><%= Post.pending.length %></span>
                  <% end %>
                <% end %>

                <% if current_user.owner? and Rails.application.multi_tenancy? %>
                  <%= link_to @header_full_urls ? get_url_for(method(:request_billing_page_url)) : request_billing_page_path, class: 'dropdown-item', data: {turbolinks: false} do %>
                    <%= t('billing.title') %>
                    <% if not Current.tenant.tenant_billing.has_active_subscription? %>
                      <span style="color: red; font-size: 18px;">⚠️</span>
                    <% end %>
                  <% end %>
                <% end %>

                <div class="dropdown-divider"></div>
              <% end %>

              <h6 class="dropdown-header"><%= t('header.menu.profile_header') %></h6>
              <%= link_to t('header.menu.profile_settings'), @header_full_urls ? get_url_for(method(:edit_user_registration_url)) : edit_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>

              <% if current_user.admin? %>
                <h6 class="dropdown-header"><%= t('header.menu.help_header') %></h6>
                <% unless @boards.empty? %>
                  <%= link_to t('header.menu.tour'), @header_full_urls ? get_url_for(method(:board_url), resource: @boards.first, options: { tour: true }) : board_path(@boards.first, tour: true), class: 'dropdown-item tourDropdown' %>
                <% end %>
                <%= link_to t('header.menu.docs'), 'https://docs.astuto.io', class: 'dropdown-item', target: '_blank' %>
                <%= link_to t('header.menu.support'), Rails.application.multi_tenancy? ? 'mailto:info@astuto.io' : 'https://github.com/astuto/astuto/issues', class: 'dropdown-item', target: '_blank' %>

                <div class="dropdown-divider"></div>
              <% end %>
              
              <% unless @disable_sign_out %>
                <%= button_to t('header.menu.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <small style="font-size: 12px; color: grey; padding: 0.25rem 1.5rem;">
                  Sign out disabled
                </small>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('header.log_in'), @header_full_urls ? get_url_for(method(:new_user_session_url)) : new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

astuto/app/views/layouts/_no_active_subscription_banner.html.erb
<div class="noActiveSubscriptionBanner">
  <% if @tenant.tenant_billing.trial? %>
    <span>Your trial has ended. Please <%= link_to 'subscribe', get_url_for(method(:request_billing_page_url)), data: {turbolinks: false} %>  to continue using our services.</span>
  <% else %>  
    <span>Your subscription has ended. Please <%= link_to 'renew your subscription', get_url_for(method(:request_billing_page_url)), data: {turbolinks: false} %> to continue using our services.</span>
  <% end %>
</div>

astuto/app/views/layouts/_page_title.html.erb
<%= @page_title %>
<% if @tenant %>
  <% if @page_title %>
    <%= " | " %>
  <% end %>
  <%= @tenant.site_name %>
<% end %>

astuto/app/views/layouts/_promo_banner.html.erb
<div class="promoBanner">
  <span>
    Want a feedback space like this?
    <a href="https://astuto.io?utm_campaign=promobanner&utm_source=feedback.astuto.io">
      Learn more
    </a>
    or
    <a href="https://login.astuto.io/signup">
      start your 7-day free trial now!
    </a>
  </span>
</div>

astuto/app/views/layouts/_set_js_locale.html.erb
<script type="text/javascript">
  // Used to set I18n-js locale to Rails locale
  // Variable used in javascript/translations/index.js.erb
  
  var LOCALE = "<%= I18n.locale %>";
  var IS_PRODUCTION = <%= Rails.env.production? %>;
</script>

astuto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= render 'layouts/page_title' %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= render 'layouts/set_js_locale' %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <% if @tenant and not @tenant.tenant_billing.has_active_subscription? and (user_signed_in? and current_user.owner?) %>
      <%= render 'layouts/no_active_subscription_banner' %>
    <% end %>

    <% if Rails.application.multi_tenancy? && @tenant && @tenant.subdomain == "feedback" %>
      <%= render 'layouts/promo_banner' %>
    <% end %>

    <% if @tenant %>
      <%= render 'layouts/header' %>
    <% end %>
    
    <%= render 'layouts/alerts' %>
    
    <div class="container">
      <%= yield %>
    </div>

    <% if @tenant and not @tenant.tenant_setting.custom_css.blank? %>
      <style type="text/css">
        <%= @tenant.tenant_setting.custom_css %>
      </style>
    <% end %>

    <% if params[:tour] == 'true' && user_signed_in? && current_user.admin? %>
      <%= react_component('Tour/Tour', { userFullName: current_user.full_name }) %>
    <% end %>
  </body>
</html>

astuto/app/views/layouts/embedded.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= render 'layouts/page_title' %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= render 'layouts/set_js_locale' %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>

    <div>
      <%= yield %>
    </div>

    <% if @tenant and not @tenant.tenant_setting.custom_css.blank? %>
      <style type="text/css">
        <%= @tenant.tenant_setting.custom_css %>
      </style>
    <% end %>
  </body>
</html>

astuto/app/views/layouts/mailer_no_style.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>