astuto/config/routes.rb
Rails.application.routes.draw do
  if !Rails.application.multi_tenancy?
    mount Rswag::Api::Engine => '/api-docs'
  end

  if Rails.application.multi_tenancy?
    constraints subdomain: 'showcase' do
      root to: 'static_pages#showcase', as: :showcase
    end

    constraints subdomain: 'api' do
      mount Rswag::Api::Engine => '/api-docs'
    end

    constraints subdomain: 'login' do
      get '/signup', to: 'tenants#new'
      get '/is_available', to: 'tenants#is_available'
      
      resource :tenants, only: [:create]
    end

    constraints subdomain: 'billing' do
      get '/billing', to: 'billing#index'
      get '/billing/return', to: 'billing#return'
      post '/create_checkout_session', to: 'billing#create_checkout_session'
      get '/session_status', to: 'billing#session_status'
      post '/webhook', to: 'billing#webhook'
    end
  end

  constraints subdomain: /.*/ do
    root to: 'static_pages#root'
    
    get '/roadmap', to: 'static_pages#roadmap'
    get '/embedded_roadmap', to: 'static_pages#embedded_roadmap'
    get '/pending-tenant', to: 'static_pages#pending_tenant'
    get '/blocked-tenant', to: 'static_pages#blocked_tenant'
    
    get '/request_billing_page', to: 'billing#request_billing_page'
    
    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :sessions => 'sessions',
      :passwords => 'passwords'
    }

    devise_scope :user do
      get '/users/send_set_password_instructions', to: 'registrations#send_set_password_instructions', as: :send_set_password_instructions
    end
    
    resources :tenants, only: [:show, :update]
    resources :users, only: [:index, :update]
    resources :o_auths, only: [:index, :create, :update, :destroy] do
      resource :tenant_default_o_auths, only: [:create, :destroy]
    end
    get '/o_auths/:id/start', to: 'o_auths#start', as: :o_auth_start
    get '/o_auths/:id/callback', to: 'o_auths#callback', as: :o_auth_callback
    get '/o_auths/sign_in_from_oauth_token', to: 'o_auths#sign_in_from_oauth_token', as: :o_auth_sign_in_from_oauth_token
  
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
      resources :follows, only: [:index]
      resource :likes, only: [:create, :destroy]
      resources :likes, only: [:index]
      resources :comments, only: [:index, :create, :update, :destroy]
      resources :post_status_changes, only: [:index]

      get '/moderation', on: :collection, to: 'posts#moderation'
    end
    
    resources :boards, only: [:index, :create, :update, :destroy, :show] do
      patch 'update_order', on: :collection
    end
  
    resources :post_statuses, only: [:index, :create, :update, :destroy] do
      patch 'update_order', on: :collection
    end

    resources :invitations, only: [:create]
    post '/invitations/test', to: 'invitations#test', as: :invitation_test

    resources :api_keys, only: [:create]
  
    namespace :site_settings do
      get 'general'
      get 'authentication'
      get 'boards'
      get 'post_statuses'
      get 'roadmap'
      get 'invitations'
      get 'appearance'
    end

    namespace :moderation do
      get 'feedback'
      get 'users'
    end

    # API routes
    namespace :api do
      namespace :v1 do
        resources :boards, only: [:index, :show, :create]
        resources :post_statuses, only: [:index]
        resources :posts, only: [:index, :show, :create, :update, :destroy] do
          member do
            put :update_board, :update_status, :approve, :reject
          end
        end
        resources :comments, only: [:index, :show, :create, :update, :destroy] do
          member do
            put :mark_as_post_update, :unmark_as_post_update
          end
        end
        resources :votes, only: [:index, :show, :create, :destroy], controller: 'likes'
        resources :users, only: [:index, :show, :create] do
          collection do
            get :get_by_email, controller: 'users', action: 'show_by_email'
          end
          member do
            put :block
          end
        end 
      end
    end
  end

  # Healthcheck endpoint
  get '/health', to: proc {
    Tenant.first # to make sure db works
    [200, {}, ['success']]
  }
end

astuto/app/controllers/site_settings_controller.rb
class SiteSettingsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_admin
  before_action :set_page_title
  
  def general
  end

  def authentication
  end

  def boards
  end

  def post_statuses
  end

  def roadmap
  end

  def invitations
    @invitations = Invitation.all.order(updated_at: :desc)
  end

  def appearance
  end

  private

    def set_page_title
      @page_title = t('header.menu.site_settings')
    end
end

astuto/app/views/site_settings/_menu.html.erb
<div class="sidebar">
  <div class="sidebarBox">
    <span class="boxTitleText"><%= t('site_settings.menu.title') %></span>
    
    <div class="verticalNavigation" role="tablist" aria-orientation="vertical">
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.general'), path: site_settings_general_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.authentication'), path: site_settings_authentication_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.boards'), path: site_settings_boards_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.post_statuses'), path: site_settings_post_statuses_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.roadmap'), path: site_settings_roadmap_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.invitations'), path: site_settings_invitations_path %>
      <%= render 'shared/sidebar_menu_link', label: t('site_settings.menu.appearance'), path: site_settings_appearance_path %>
    </div>
  </div>
</div>

astuto/app/views/site_settings/appearance.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Appearance',
        {
          originForm: {
            customCss: @tenant_setting.custom_css,
          },
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/authentication.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Authentication',
        {
          originForm: {
            emailRegistrationPolicy: @tenant_setting.email_registration_policy,
            allowedEmailDomains: @tenant_setting.allowed_email_domains,
          },
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/boards.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Boards',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/general.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/General',
        {
          originForm: {
            siteName: @tenant.site_name,
            siteLogo: @tenant.site_logo,
            brandDisplaySetting: @tenant_setting.brand_display,
            showVoteCount: @tenant_setting.show_vote_count,
            showVoteButtonInBoard: @tenant_setting.show_vote_button_in_board,
            hideUnusedStatusesInFilterByStatus: @tenant_setting.hide_unused_statuses_in_filter_by_status,
            showPoweredBy: @tenant_setting.show_powered_by,
            rootBoardId: @tenant_setting.root_board_id.to_s,
            customDomain: @tenant.custom_domain,
            isPrivate: @tenant_setting.is_private,
            allowAnonymousFeedback: @tenant_setting.allow_anonymous_feedback,
            feedbackApprovalPolicy: @tenant_setting.feedback_approval_policy,
            logoLinksTo: @tenant_setting.logo_links_to,
            logoCustomUrl: @tenant_setting.logo_custom_url,
            showRoadmapInHeader: @tenant_setting.show_roadmap_in_header,
            collapseBoardsInHeader: @tenant_setting.collapse_boards_in_header,
            locale: @tenant.locale,
            useBrowserLocale: @tenant_setting.use_browser_locale,
          },
          boards: @tenant.boards.order(order: :asc),
          isMultiTenant: Rails.application.multi_tenancy?,
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/invitations.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Invitations',
        {
          siteName: Current.tenant.site_name,
          invitations: @invitations,
          currentUserEmail: current_user.email,
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/post_statuses.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/PostStatuses',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

astuto/app/views/site_settings/roadmap.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Roadmap',
        {
          embeddedRoadmapUrl: get_url_for(method(:embedded_roadmap_url)),
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>